version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - |
        pip install pylint
  build:
    commands:
    # linting 3 different places with python files
      - |
        pylint ./source
        pylint ./tests
        pylint ./devops
