swagger: "2.0"
info:
  description: <REPLACE>
  version: <REPLACE>
  title: <REPLACE>
host: <REPLACE>
basePath: <REPLACE>
schemes:
  - https
paths:
  /token:
    get:
      parameters:
        - name: code
          in: query
          required: true
          type: string
      responses: {}
      x-amazon-apigateway-integration:
        credentials: arn:aws:iam::414275662771:role/ev-chart/apigateway/ApplicationInfrastructure-ApiGatewayRestApiResourc-XBOTAQ05XU57
        httpMethod: POST
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:414275662771:function:ApplicationInfrastructureStack-Lamb-LambdaFunction-bwbdBD0JaxjS/invocations
        passthroughBehavior: when_no_match
        type: aws_proxy
x-amazon-apigateway-binary-media-types:
  - "*/*"
